services:
  coturn:
    image: coturn/coturn
    container_name: coturn
    restart: unless-stopped
    ports:
      - "3478:3478"        # TURN TCP port
      - "3478:3478/udp"    # TURN UDP port
      - "5349:5349"        # TLS TURN TCP
      - "5349:5349/udp"    # TLS TURN UDP
      - "50000-50800:50000-50800/udp" # UDP relay ports range
    environment:
      - TURN_USER=turnuser
      - TURN_PASSWORD=turnpassword
      - REALM=defencecomm.local
      - LISTENING_PORT=3478
      - MIN_PORT=50000
      - MAX_PORT=50800
    command: >
      /bin/sh -c "turnserver
        --min-port=50000
        --max-port=50800
        --realm=defencecomm.local
        --user=turnuser:turnpassword
        --lt-cred-mech
        --no-multicast-peers
        --listen-ip=0.0.0.0
        --external-ip=115.187.53.16
        --fingerprint"
